In [ ]:
name = input("Enter your name please : \n")
weight = int(input("Enter the Weight : \n"))

print("Dear " + name + ", your weight is " + str(weight) + " in Kgs")

Enter your name please : 
liq
Enter the Weight : 
80
Dear liq, your weight is 80 in Kgs


In [ ]:
print("Hello ",name,",Your age is ",age," years.")
print(f"Dear {name}, your weight is {weight} in Kgs")

Dear liq, your weight is 80 in Kgs


Conditions

In [ ]:
temp = int(input("Enter the Temperature : \n"))

if temp > 30:
  print("It's a hot day")

elif temp < 12:
  print("It's a cold day")

else:
  print("It's a pleasant day")

Enter the Temperature : 
14
It's a pleasant day


Assigment 1:
1. Take the user name of user:
2. username should be in between 3-10 chars
3. if not, then give the error message to the user

In [ ]:
high_income = True
good_credit_score = False

if high_income and good_credit_score:
  print("Eligible for loan")

else:
  print("Not Eligible")

Not Eligible


In [ ]:
high_income = True
good_credit_score = False

if high_income or good_credit_score:
  print("Eligible for loan")

else:
  print("Not Eligible")

Eligible for loan


Assigmnet 2:
1. Price of the house is 500000
2. Check credit history of loan applicant
3. If they have good ch, they pay 10% as down payment
4. If they don't have good ch, they pay 20% as down payment
5. This conditions have to be printed along with exact amount to be paid

In [ ]:
for number in range(5):
  print(number)


0
1
2
3
4


In [ ]:
number 


4

In [ ]:
for number in range(0,10,2):
  print(number)


print("done")

0
2
4
6
8
done


In [ ]:
for number in range(5):
  print("Iteration", number)

Iteration 0
Iteration 1
Iteration 2
Iteration 3
Iteration 4


In [ ]:
for number in range(5):
  print("Iteration", number, number *"*")

Iteration 0 
Iteration 1 *
Iteration 2 **
Iteration 3 ***
Iteration 4 ****


In [ ]:
i = 1
while i <= 5:
  print('*' * i)
  i += 1 # i = i + 1 - Augmented Operator

print("Done")

*
**
***
****
*****
Done


In [ ]:
help = input(">")
while help.lower() == "help":
  print("start: to start the car")
  print("stop: to stop the car")
  break

else:
  print("Invalid input")

>Help
start: to start the car
stop: to stop the car


In [ ]:
list1 = [10, 12, 30, 40, 45]

In [ ]:
list2 = [32,45,32,12,23]

In [ ]:
type(list1)

list

In [ ]:
letters = ["a","b","c","d","e"]

In [ ]:
mix = [1,2,3,4, "a","b"]

In [ ]:
list3 = list1 + list2

In [ ]:
list3

[10, 12, 30, 40, 45, 32, 45, 32, 12, 23]

In [ ]:
list1 = list(range(15))

In [ ]:
list1

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14]

In [ ]:
list2.sort()

In [ ]:
list2

[12, 23, 32, 32, 45]

In [ ]:
list2.append(20)

In [ ]:
list2

[12, 23, 32, 32, 45, 20]

In [ ]:
list2.insert(2, 15)

In [ ]:
list2

[12, 23, 15, 32, 32, 45, 20]

In [ ]:
list2.pop()

20

In [ ]:
list2

[12, 23, 15, 32, 32, 45]

In [ ]:
char = list("Hello World")

In [ ]:
char

['H', 'e', 'l', 'l', 'o', ' ', 'W', 'o', 'r', 'l', 'd']

In [ ]:
list2 

[12, 23, 15, 32, 32, 45]

In [ ]:
list2[1]

23

In [ ]:
list2[1] = 55

In [ ]:
list2

[12, 55, 15, 32, 32, 45]

In [ ]:
point = (1,2,3,4)

In [ ]:
point

(1, 2, 3, 4)

In [ ]:
type(point)

tuple

In [ ]:
point[2] = 5

TypeError: ignored

In [ ]:
prices = [10,20,24,12,45]
total = 0
for item in prices:
  total += item
  #print(total) 

print(total)

111


Similarly find the max number in a list

In [ ]:
dict1 = {"x":1,
         "y":2}

In [ ]:
type(dict1)

dict

In [ ]:
dict1

{'x': 1, 'y': 2}

In [ ]:
dict1.keys()

dict_keys(['x', 'y'])

In [ ]:
dict1.values()

dict_values([1, 2])

In [ ]:
dict1["x"]

1

In [ ]:
dict2 = {"x":[1,2,3,4],
         "y":2}

In [ ]:
dict2["x"]

[1, 2, 3, 4]

In [ ]:
dict2 = {"x":[1,2,3,4],
         "y":[1,2,3,4]}

In [ ]:
dict2

{'x': [1, 2, 3, 4], 'y': [1, 2, 3, 4]}

In [ ]:
dict2["z"] = [10,20,30]

In [ ]:
dict2

{'x': [1, 2, 3, 4], 'y': [1, 2, 3, 4], 'z': [10, 20, 30]}

Functions

1. user defined
2. pre-defined

In [ ]:
def greet_user():
  print("Hi there...")
  print("Welcome aboard")

In [ ]:
print("start")
greet_user()
print("stop")

start
Hi there...
Welcome aboard
stop


In [ ]:
def greet_user(first, last): #-- Parameters
  print(f"Hi {first} {last}")
  print("Welcome aboard")

In [ ]:
print("start")
greet_user(last="Manna",first="Liqzan") #-- Arguments
print("stop")

start
Hi Liqzan Manna
Welcome aboard
stop


Functions:
1. Performs a task
2. Returns a value

Modules and Libraries

In [ ]:
import math

In [ ]:
math.factorial(4)

24

In [ ]:
import time

In [ ]:
for i in range(0,10):
  print(i)
  time.sleep(0.5)

0
1
2
3
4
5
6
7
8
9


In [ ]:
import numpy as np


In [ ]:
n = numpy.array([2,3,4,5,6])

In [ ]:
n

array([2, 3, 4, 5, 6])

In [ ]:
type(n)

numpy.ndarray

In [ ]:
n = np.array([2,3,4,5,6])

In [ ]:
n.ndim

1

In [ ]:
n.shape

(5,)

In [ ]:
n.size

5

In [ ]:
n2 = np.array([[1,2],[3,4]])

In [ ]:
n2

array([[1, 2],
       [3, 4]])

In [ ]:
n2.ndim

2

In [ ]:
n2.shape

(2, 2)

In [ ]:
n2.size

4

In [ ]:
n2

array([[1, 2],
       [3, 4]])

In [ ]:
n2[0,1]

2

In [ ]:
n2[1,0]

3

In [ ]:
a = np.array([1,2,3,4,5])
b = np.array([6,7,8,9,10])

In [ ]:
a

array([1, 2, 3, 4, 5])

In [ ]:
b

array([ 6,  7,  8,  9, 10])

In [ ]:
c = [1,2,3,4,5]
d = [6,7,8,9,10]

In [ ]:
c

[1, 2, 3, 4, 5]

In [ ]:
d

[6, 7, 8, 9, 10]

In [ ]:
c * d

TypeError: ignored

In [ ]:
a * b

array([ 6, 14, 24, 36, 50])

In [ ]:
a = np.array([[[1,2],
              [3,4]],
              [[5,6],
               [7,8]]])

In [ ]:
a.ndim

3

In [ ]:
a.shape

(2, 2, 2)

In [ ]:
a[0,1,0]

3

In [ ]:
a

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [ ]:
a[1,1,0]

7

In [ ]:
k = np.arange(0,18)

In [ ]:
k


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17])

In [ ]:
k = k.reshape(3,6)

In [ ]:
k

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17])

In [ ]:
k.reshape(2,9)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16, 17]])

In [ ]:
k

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17]])

In [ ]:
k[0:2,2:4]

array([[2, 3],
       [8, 9]])

In [ ]:
a = np.zeros((2,3))

In [ ]:
a

array([[0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
a = np.zeros((2,3,3))

In [ ]:
a

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [ ]:
a = np.ones((2,3,3))

In [ ]:
a

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

In [ ]:
i = np.eye(3)

In [ ]:
i

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
f = np.full((3,3), 12)

In [ ]:
f

array([[12, 12, 12],
       [12, 12, 12],
       [12, 12, 12]])

In [ ]:
f = np.full((3,3), '*')

In [ ]:
f

array([['*', '*', '*'],
       ['*', '*', '*'],
       ['*', '*', '*']], dtype='<U1')