Numpy is a general-purpose array-processing package. It provides a high-performance multidimensional array object, and tools for working with these arrays. It is the fundamental package for scientific computing with Python.

In [1]:
import numpy as np

arr = np.array([1,2,3])
print((arr))

[1 2 3]


In [5]:
arr = np.array([[1,2,3],
               [4,5,6]])
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [9]:
arr = np.array((1,2,3))
list(arr)

[1, 2, 3]

Accessing the array Index
In a numpy array, indexing or accessing the array index can be done in multiple ways. To print a range of an array, slicing is done. Slicing of an array is defining a range in a new array which is used to print a range of elements from the original array. Since, sliced array holds a range of elements of the original array, modifying content with the help of sliced array modifies the original array content.

In [2]:
import numpy as np

arr = np.array([[-1,2,0,4],
               [4,-0.5,6,0],
               [2.6,0,7,8],
               [3,-7,4,2]])
print(arr)
arr.shape

[[-1.   2.   0.   4. ]
 [ 4.  -0.5  6.   0. ]
 [ 2.6  0.   7.   8. ]
 [ 3.  -7.   4.   2. ]]


(4, 4)

In [3]:
arr[:2,::2] #array with first two rows and alternate columns(0 and 2)

array([[-1.,  0.],
       [ 4.,  6.]])

Basic Array Operations
In numpy, arrays allow a wide range of operations which can be performed on a particular array or a combination of Arrays. These operation include some basic Mathematical operation as well as Unary and Binary operations.

In [4]:
a = np.array([[1,2],[3,4]])
b = np.array([[4,3],[2,1]])
print(a+1)
print(b-2)
a*b

[[2 3]
 [4 5]]
[[ 2  1]
 [ 0 -1]]


array([[4, 6],
       [6, 4]])

Constructing a Datatype Object
In Numpy, datatypes of Arrays need not to be defined unless a specific datatype is required. Numpy tries to guess the datatype for Arrays which are not predefined in the constructor function.

In [23]:
x = np.array([1,2])
#print(x.dtype)

y = np.array([1.0,2.0])
#print(y.dtype)

z = np.array(['1','2'], dtype = 'U8')
#print(z.dtype)
z

array(['1', '2'], dtype='<U8')

Array in Numpy is a table of elements (usually numbers), all of the same type, indexed by a tuple of positive integers. In Numpy, number of dimensions of the array is called rank of the array.A tuple of integers giving the size of the array along each dimension is known as shape of the array. An array class in Numpy is called as ndarray. Elements in Numpy arrays are accessed by using square brackets and can be initialized by using nested Python Lists.

In [25]:
arr = np.array([[1,2,3],
               [4,2,5]])
print(type(arr))
print(arr.ndim)
print(arr.shape)
print(arr.size)
arr

<class 'numpy.ndarray'>
2
(2, 3)
6


array([[1, 2, 3],
       [4, 2, 5]])

Knowing the basics of array indexing is important for analysing and manipulating the array object. NumPy offers many ways to do array indexing.

Slicing: Just like lists in python, NumPy arrays can be sliced. As arrays can be multidimensional, you need to specify a slice for each dimension of the array.
Integer array indexing: In this method, lists are passed for indexing for each dimension. One to one mapping of corresponding elements is done to construct a new arbitrary array.
Boolean array indexing: This method is used when we want to pick elements from array which satisfy some condition.

In [35]:
arr = np.array([[-1,2,0,4],
               [4,-0.5,6,0],
               [2.6,0,7,8],
               [3,-7,4,2]])

#Slicing array
temp = arr[:2,::2]



cond = arr > 2
temp1 = arr[cond]

temp1

array([4. , 4. , 6. , 2.6, 7. , 8. , 3. , 4. ])

Indexing using index arrays

Indexing can be done in numpy by using an array as an index. In case of slice, a view or shallow copy of the array is returned but in index array a copy of the original array is returned. Numpy arrays can be indexed with other arrays or any other sequence with the exception of tuples. The last element is indexed by -1 second last by -2 and so on.

In [39]:
a = np.arange(10,1,-2)
a

array([10,  8,  6,  4,  2])

Types of Indexing
There are two types of indexing :

Basic Slicing and indexing : Consider the syntax x[obj] where x is the array and obj is the index. Slice object is the index in case of basic slicing. Basic slicing occurs when obj is :

a slice object that is of the form start : stop : step
an integer
or a tuple of slice objects and integers

In [46]:
a = np.arange(20)
print(a)

a[-8:17:1]
a[10:]



[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

Numpy | Iterating Over Array
NumPy package contains an iterator object numpy.nditer. It is an efficient multidimensional iterator object using which it is possible to iterate over an array. Each element of an array is visited using Python’s standard Iterator interface.

In [55]:
a
a.reshape(4,5)

print('Modified Array:')
for x in np.nditer(a):
    print(x)

Modified Array:
0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19


Numpy | Linear Algebra
The Linear Algebra module of NumPy offers various methods to apply linear algebra on any numpy array.
One can find:

rank, determinant, trace, etc. of an array.
eigen values of matrices
matrix and vector products (dot, inner, outer,etc. product), matrix exponentiation
solve linear or tensor equations and much more!

In [61]:
A = np.array([[6,1,1],
            [4,-2,5],
            [2,8,7]])
print('Rank of Matrix:', np.linalg.matrix_rank(A))
print('Trace of Matrix:', np.trace(A))
print('Determinant of Matrix:', np.linalg.det(A))
print('Inverse of Matrix:', np.linalg.inv(A))
print('Power of Matrix:', np.linalg.matrix_power(A,3))


Rank of Matrix: 3
Trace of Matrix: 11
Determinant of Matrix: -306.0
Inverse of Matrix: [[ 0.17647059 -0.00326797 -0.02287582]
 [ 0.05882353 -0.13071895  0.08496732]
 [-0.11764706  0.1503268   0.05228758]]
Power of Matrix: [[336 162 228]
 [406 162 469]
 [698 702 905]]
