# DATA PREPROCESSING STEP

In [1]:
#Import the Library
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
#Import the dataset
dataset = pd.read_csv('DATA.CSV')
dataset

Country   Age   Salary Purchased
0   France  22.0  72000.0       Yes
1  Germany  34.0  81000.0        No
2    Spain  25.0  10000.0       Yes
3   France   NaN  15000.0        No
4  Germany  25.0      NaN       Yes
5    Spain  26.0  17000.0        No
6   France  28.0  19000.0       Yes
7  Germany  29.0  22000.0        No

In [3]:
X = dataset.iloc[:,:-1].values #independent
X

array([['France', 22.0, 72000.0],
       ['Germany', 34.0, 81000.0],
       ['Spain', 25.0, 10000.0],
       ['France', nan, 15000.0],
       ['Germany', 25.0, nan],
       ['Spain', 26.0, 17000.0],
       ['France', 28.0, 19000.0],
       ['Germany', 29.0, 22000.0]], dtype=object)

In [4]:
y = dataset.iloc[:,-1].values
y

array(['Yes', 'No', 'Yes', 'No', 'Yes', 'No', 'Yes', 'No'], dtype=object)

In [8]:
# Taking Care of the Missing of the Value
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values = np.nan,strategy = 'mean')
imputer.fit(X[:,1:3])
X[:,1:3] = imputer.transform(X[:,1:3])

In [13]:
X[:,1:3]

array([[22.0, 72000.0],
       [34.0, 81000.0],
       [25.0, 10000.0],
       [27.0, 15000.0],
       [25.0, 33714.28571428572],
       [26.0, 17000.0],
       [28.0, 19000.0],
       [29.0, 22000.0]], dtype=object)

In [14]:
#  Encoding the Categorical Data
# Indepent Variable
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers = [('encoder',OneHotEncoder(),[0])], remainder = 'passthrough')
X = np.array(ct.fit_transform(X))

In [16]:
print(X)

[[1.0 0.0 0.0 22.0 72000.0]
 [0.0 1.0 0.0 34.0 81000.0]
 [0.0 0.0 1.0 25.0 10000.0]
 [1.0 0.0 0.0 27.0 15000.0]
 [0.0 1.0 0.0 25.0 33714.28571428572]
 [0.0 0.0 1.0 26.0 17000.0]
 [1.0 0.0 0.0 28.0 19000.0]
 [0.0 1.0 0.0 29.0 22000.0]]


In [17]:
# LabelEncodimng in the dependent variable
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)

In [18]:
y

array([1, 0, 1, 0, 1, 0, 1, 0])

In [31]:
# Split the dataset into the training and the test set
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size = 0.2,random_state = 2)
X_train

array([[1.0, 0.0, 0.0, 28.0, 19000.0],
       [0.0, 0.0, 1.0, 25.0, 10000.0],
       [1.0, 0.0, 0.0, 27.0, 15000.0],
       [0.0, 1.0, 0.0, 29.0, 22000.0],
       [0.0, 0.0, 1.0, 26.0, 17000.0],
       [1.0, 0.0, 0.0, 22.0, 72000.0]], dtype=object)

In [32]:
X_test

array([[0.0, 1.0, 0.0, 25.0, 33714.28571428572],
       [0.0, 1.0, 0.0, 34.0, 81000.0]], dtype=object)

In [34]:
y_test

array([1, 0])

In [35]:
y_train

array([1, 1, 0, 0, 0, 1])

In [36]:
# Feature Scaling
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train[:,3:] = sc.fit_transform(X_train[:,3:])
X_test[:,3:] = sc.transform(X_test[:,3:])

In [37]:
X_train

array([[1.0, 0.0, 0.0, 0.808736084303188, -0.3258383897338395],
       [0.0, 0.0, 1.0, -0.5146502354656659, -0.7549913908467014],
       [1.0, 0.0, 0.0, 0.36760731104690336, -0.5165730568951115],
       [0.0, 1.0, 0.0, 1.2498648575594726, -0.18278738936288555],
       [0.0, 0.0, 1.0, -0.0735214622093813, -0.4212057233144755],
       [1.0, 0.0, 0.0, -1.83803655523452, 2.201395950153014]],
      dtype=object)

In [38]:
X_test

array([[0.0, 1.0, 0.0, -0.5146502354656659, 0.37579270732369674],
       [0.0, 1.0, 0.0, 3.455508723840896, 2.630548951265876]],
      dtype=object)

In [43]:
# Feature Scaling
from sklearn.preprocessing import MinMaxScaler
mm = MinMaxScaler()
X_train[:,3:] = mm.fit_transform(X_train[:,3:])
X_test[:,3:] = mm.transform(X_test[:,3:])

In [42]:
X_test

array([[0.0, 1.0, 0.0, 0.4285714285714286, 0.38248847926267293],
       [0.0, 1.0, 0.0, 1.7142857142857144, 1.145161290322581]],
      dtype=object)