# LOGISTIC REGRESSION

In [1]:
#Import the Library
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [3]:
#Import the dataset
dataset = pd.read_csv('Social_Network_Ads.csv')
dataset
X = dataset.iloc[:,:-1].values #independent
y = dataset.iloc[:,-1].values

In [7]:
# Taking Care of the Missing of the Value
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values = np.nan,strategy = 'mean')
imputer.fit(X)
X = imputer.transform(X)

In [11]:
# Split the dataset into the training and the test set
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size = 0.2,random_state = 2)

In [12]:
X_test

array([[2.90e+01, 8.30e+04],
       [2.10e+01, 1.60e+04],
       [3.70e+01, 5.30e+04],
       [2.90e+01, 7.50e+04],
       [5.40e+01, 7.00e+04],
       [4.70e+01, 2.00e+04],
       [2.30e+01, 8.20e+04],
       [2.80e+01, 3.20e+04],
       [4.00e+01, 6.00e+04],
       [3.60e+01, 1.26e+05],
       [2.40e+01, 2.30e+04],
       [2.20e+01, 2.70e+04],
       [3.20e+01, 1.17e+05],
       [4.50e+01, 7.90e+04],
       [3.50e+01, 5.90e+04],
       [3.30e+01, 4.30e+04],
       [1.90e+01, 7.00e+04],
       [6.00e+01, 4.20e+04],
       [5.30e+01, 7.20e+04],
       [2.60e+01, 4.30e+04],
       [3.70e+01, 7.80e+04],
       [4.50e+01, 4.50e+04],
       [3.00e+01, 6.20e+04],
       [3.60e+01, 3.30e+04],
       [2.50e+01, 8.00e+04],
       [4.50e+01, 3.20e+04],
       [4.50e+01, 2.20e+04],
       [4.00e+01, 5.70e+04],
       [4.40e+01, 1.39e+05],
       [3.20e+01, 1.00e+05],
       [2.40e+01, 5.50e+04],
       [4.10e+01, 5.20e+04],
       [4.60e+01, 2.30e+04],
       [3.80e+01, 5.90e+04],
       [3.20e+

In [13]:
# Feature Scaling
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [14]:
X_test

array([[-0.84826272,  0.40218125],
       [-1.62050759, -1.57325199],
       [-0.07601785, -0.48234109],
       [-0.84826272,  0.16630863],
       [ 1.56500249,  0.01888824],
       [ 0.88928823, -1.45531567],
       [-1.42744637,  0.37269718],
       [-0.94479333, -1.10150673],
       [ 0.21357397, -0.27595254],
       [-0.17254846,  1.66999662],
       [-1.33091576, -1.36686344],
       [-1.52397698, -1.24892713],
       [-0.5586709 ,  1.40463991],
       [ 0.69622701,  0.28424494],
       [-0.26907907, -0.30543662],
       [-0.46214029, -0.77718187],
       [-1.8135688 ,  0.01888824],
       [ 2.14418614, -0.80666595],
       [ 1.46847188,  0.07785639],
       [-1.13785454, -0.77718187],
       [-0.07601785,  0.25476086],
       [ 0.69622701, -0.71821372],
       [-0.75173211, -0.21698439],
       [-0.17254846, -1.07202266],
       [-1.23438515,  0.31372902],
       [ 0.69622701, -1.10150673],
       [ 0.69622701, -1.39634752],
       [ 0.21357397, -0.36440478],
       [ 0.5996964 ,

In [15]:
# Training the Logistic Regression Model on the Training Set
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression(random_state = 2)
classifier.fit(X_train,y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=2, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [21]:
#Prediction
print(classifier.predict(sc.transform([[35,88000]])))

[0]


In [19]:
y_pred = classifier.predict(X_test)
print(np.concatenate((y_pred.reshape(len(y_pred),1),y_test.reshape(len(y_test),1)),1))

[[0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 1]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 1]
 [1 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [0 1]
 [0 1]
 [0 0]
 [0 0]
 [0 0]
 [0 1]
 [0 1]
 [0 0]
 [1 1]
 [0 1]
 [0 0]
 [0 0]
 [0 1]
 [0 0]
 [1 1]
 [0 1]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [1 0]
 [0 0]
 [1 1]
 [0 0]
 [0 1]
 [1 1]
 [0 0]
 [0 1]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [1 0]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [0 1]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [0 0]]
